version: '3.9'
services:
    nginx:
        build:
          context: .
          dockerfile: ./dockerfiles/nginx/nginx.dockerfile
        container_name: clinica_nginx
        restart: always
        depends_on:
            - php
            - mysql
        environment:
          - CERT_DOMAIN=${DOMAIN_NAME}
        volumes:
            - "./conf/nginx/local.conf:/etc/nginx/conf.d/default.conf"
            - "clinica-cert-data:/etc/nginx/certs/"
        ports:
            - 9090:9090
volumes:
  clinica-db-data:
  clinica-cert-data: